version: '3.8'

services:
  web:
    build: .
    container_name: spacex_project
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    command: poetry run python manage.py runserver 0.0.0.0:8000
